### ISSUE TITLE
Throwout with button

### ISSUE THREAD

**Issue by akilah007** [gajus/angular-swing#13]
I want make throw out with button exactly as Tinder  in controller $scope

**Comment by barinali** [comment]
I think you can do it manually. But I need to inform you. I need to completely remove current card in the stack in my case. When I need action like that, I did it with the following;

```
$scope.throwOut = function () {
  $element = $element.closest('li[swing-card]:last');
  $element.addClass('animated rotateOutUpLeft');

  # this will work when animate is completed.
  $timeout(function () {
    $scope.cards.splice(-1);
  }, 400);
};
```
So as you see, I used [animate.css](https://daneden.github.io/animate.css/) to animate the current card. Then I removed the card when animate is completed.

If you need to keep the card in the stack after action, I think it's a little bit complex than this. Maybe you can do it to just modify the animation.

**Comment by goncalomarques** [comment]
This could be solved with card.throwOut, or not? See [the original, not angular wrapped, docs](https://github.com/gajus/swing#throwing-card-out-of-the-stack)

@gajus what would it take to do this?
