### ISSUE TITLE
Unknown provider: tProvider <- t <- swingStackDirective

### ISSUE THREAD

**Issue by najiji** [gajus/angular-swing#18]
The plugin doesn't work for me. I'm using Angular 1.4.8. ANy ideas?

**Comment by marcelaraujo** [comment]
Could you provide an example on JSFiddle?

**Comment by najiji** [comment]
I can't provide one right now, but I found out that the error only occurs when using the minified version.

**Comment by marcelaraujo** [comment]
Hummm... ok

I know what is happening. I gonna fix it today.

Thank you

**Comment by marcelaraujo** [comment]
Fixed.
