### ISSUE TITLE
LIbrary is totally broken

### ISSUE THREAD

**Issue by adelura** [gajus/angular-swing#20]
After merging https://github.com/gajus/angular-swing/pull/15 you can't throw out card. After merging https://github.com/gajus/angular-swing/pull/19 library is not working at all - you can not play with cards.

Steps to reproduce:

1. Clone repository
2. `npm i`
3. Open example.

On [develop](https://github.com/gajus/angular-swing/tree/develop) everything is working fine. I updated angular version to 1.4.7 in [bower.json](https://github.com/gajus/angular-swing/blob/master/bower.json) file on develop and everything is still okay.

Sorry to saying that, but everything is broken after recent changes from @marcelaraujo :( Anyway, swing is so cool library.

**Comment by marcelaraujo** [comment]
Ok. I will review this changes.

**Comment by gajus** [comment]
@marcelaraujo Thank you for maintaining angular-swing. :+1:

**Comment by marcelaraujo** [comment]
@adelura I found what is broken. In the develop branch, the Swing version is older and in the master branch, I've updated to latest version.

I am working to fix it what is needed to work with Swing latest version.

**Comment by syrys** [comment]
still completely broken. any update on a usable version? the current version just doesnt work at all, and no errors being thrown either.

**Comment by marcelaraujo** [comment]
I will fix it soon. My daughter has born last week and I am busy a lot. Sorry!

**Comment by syrys** [comment]
haha, somethings are more important, take your time. i will stick to 1.0 for the time being and upgrade when you get around to updating :D Would be great if you dont mind responding here when you do make the fix. if i get around to fixing it my self, i will let you know (for the time being, 1.0 works fine for me, i stole it off the examples: http://gajus.com/sandbox/angular-swing/dist/angular-swing.js).

**Comment by marcelaraujo** [comment]
Sure. I will let u know. Thanks

**Comment by bliitzkrieg** [comment]
+1

**Comment by sjmorrow** [comment]
Found what was causing the issue and created a PR for it. I understand that @marcelaraujo is busy with being a new father (congratulations!), so if anyone needs this library with all the latest additions in the swing base lib, you can use my fork. 

https://github.com/sjmorrow/angular-swing

**Comment by marcelaraujo** [comment]
Thanks a lot for @sjmorrow and for your patience @syrys.

It has been merged with lastest changes.
