### ISSUE TITLE
Create a way to access the methods from a directive

### ISSUE THREAD

**Issue by tlaverdure** [gajus/angular-swing#4]
It would be cool if there were a way to access the methods to trigger throwing the objects from a directive. So that you could easily place links to throw to the left or right.

**Comment by ajduke** [comment]
+1

**Comment by eklingkeetup** [comment]
Does anybody can find a way to map the original swing methods into the angular directive?

**Comment by barinali** [comment]
@eklingkeetup; I am using like this on a while for temporary;

I replaced these lines in swingStack directive;
```javascript
var stack;
stack = Swing.Stack();
```
with this;
```javascript
$window.stack = Swing.Stack();
```

and I use original swing stack methods with;
```javascript
$window.stack.on('eventName', function(e) { ... });
```

Yes, I know. It doesn't look good. It isn't best practice. Even, it's maybe anti-pattern. But, it works.
