### ISSUE TITLE
Remove/Add random cards in throw-confidence example

### ISSUE THREAD

**Issue by cezarant** [gajus/angular-swing#9]
Hi my friend. Very nice job! :) 
I try remove cards in throw-confidence example, without use angular, but not have sucess.
Has one method like "stack.remove(cardElement)" ? 

Don't have too much experiente in Angular, i'm a newbie in javascript...rsrs 
I'm Brazilian.  Sorry for my bad english language.

**Comment by barryvdh** [comment]
You have to call

**Comment by barryvdh** [comment]
You have to call `$scope.$digest()` after changing/removing the scope cards.

**Comment by cezarant** [comment]
thank's my friend
